version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "8081:80"
        volumes:
            - ./eccube:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
    php:
        build: php
        volumes:
            - ./eccube:/code

    mysql1:
        image: mysql:5.7
        environment:
            - TZ=Asia/Tokyo
            - LANG=ja_JP.UTF-8
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_USER=root
            - MYSQL_PASSWORD=password
        ports:
            - "3306:3306"

    # mail:
    #     image: schickling/mailcatcher
    #     ports:
    #         - "1080:1080"
    #         - "1025:1025"
