version: '2'

services:
    app:
        build: app
        # container_name: ec_cube_app
        volumes:
            - ./chokuhan:/var/www/html
        ports:
            - "8080:80"
            - "8443:443"
        environment:
            - TZ=Asia/Tokyo
            - LANG=ja_JP.UTF-8
        # stdin_open: true
        # tty: true
        depends_on:
          - postgres

    # mysql:
    #     image: mysql:5.7
    #     environment:
    #         - TZ=Asia/Tokyo
    #         - LANG=ja_JP.UTF-8
    #         - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    #         - MYSQL_USER=root
    #         - MYSQL_PASSWORD=password
    #     ports:
    #         - "3308:3306"

    postgres:
        build: postgres
        environment:
            - TZ=Asia/Tokyo
            - LANG=ja_JP.UTF-8
        ports:
            - "5435:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    # mail:
    #     image: schickling/mailcatcher
    #     ports:
    #         - "1080:1080"
    #         - "1025:1025"
